apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: notes-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-csi-gp3 # Update this line
  resources:
    requests:
      storage: 10Gi
